#
# This is popup help messages for the Admin Panel -> Settings -> Tickets
#
# Fields:
# title - Shown in bold at the top of the popover window
# content - The body of the help popover
# links - List of links shows below the content
#   title - Link title
#   href - href of link (links starting with / are translated to the
#       helpdesk installation path)
#
# The key names such as 'helpdesk_name' should not be translated as they
# must match the HTML #ids put into the page template.
#
---
number_format:
    title: Числовой формат заявок
    content: >
        Этот параметр используется для генерации номеров заявок. Используйте
        символ решетки (`#`) для обозначения числовых позиций. Прочий текст в форматировании
        будет сохранен. <span class="doc-desc-title">Разделы
        помощи</span> могут иметь собственный числовой формат.
        <br/><br/>
        Например, для шестизначных номеров используется <code>######</code>.

sequence_id:
    title: Порядок следования номеров
    content: >
        Выберите порядок следования чисел при выборе следующего номера заявки.
        Система может использовать как порядок по возрастанию, так и произвольный.
        Вы можете создать любое количество порядков по своему усмотрению. Используйте
        различные параметры <span class="doc-desc-title">Числовых форматов заявок
        </span> для разделов помощи.

default_ticket_status:
    title: Состояние для новых заявок по умолчанию
    content: >
        Выберите состояние для новых заявок по умолчанию. По желанию этот параметр может быть определен
        для различных разделов помощи. Этот параметр может быть перезаписан фильтром заявок.
    links:
      - title: Управление состояниями заявок
        href: /scp/lists.php?type=ticket-status

default_sla:
    title: План SLA по умолчанию
    content: >
        Выберите соглашению об уровне услуг (SLA) для определения сроков исполнения заявок.
    links:
      - title: Создать план SLA
        href: /scp/slas.php

default_priority:
    title: Приоритет по умолчанию
    content: >
        Выберите <span class="doc-desc-title">приоритет</span> по умолчанию для заявок, для которых
        приоритет не был назначен автоматически.
        <br/><br/>
        Приоритет может быть изменен через раздел помощи, отдел или фильтр заявок.

maximum_open_tickets:
    title: Максимальный предел открытых заявок
    content: >
        Укажите максимальное <em>количество</em> заявок от пользователя, которое разрешено держать
        <strong>открытыми</strong> в системе заявок.
        <br><br>
        Укажите <span class="doc-desc-opt">0</span>, если требуется отключить это ограничение.

agent_collision_avoidance:
    title: Избегать блокировок заявок сотрудником
    content: >
        Укажите продолжительность времени, в течение которого сотрудник может удерживать заявку
        не проявляя активности.
        <br><br>
        Укажите <span class="doc-desc-opt">0</span>, если требуется отключить это ограничение.

email_ticket_priority:
    title: Приоритет назначается в email
    content: >
        Использовать приоритет письма электронной почты службы отправителя

show_related_tickets:
    title: Показывать схожие заявки
    content: >
        Показывать все схожие заявки при входе пользователя - иначе доступ ограничен одной
        заявкой на учетную запись

human_verification:
    title: Проверка против роботов
    content: >
        Включить CAPTCHA в клиентской части портала для проверки активности на человечность.
        <br><br>
        Требуется библиотека GDLib

claim_tickets:
    title: Назначать заявку ответившему
    content: >
        Включите этот параметра для автоматического назначения не назначенной заявки на отвечающего сотрудника.
        <br><br>
        Открытые заново заявки всегда назначаются последнему отвечающему.

assigned_tickets:
    title: Назначенные заявки
    content: >
        Включите этот параметр для того, чтобы исключить назначенные заявки из <span class="doc-desc-title">Очереди
        открытых заявок</span>.

answered_tickets:
    title: Закрытые заявки
    content: >
        Включите этот параметр для отображения закрытых заявок в <span
        class="doc-desc-title">Очереди закрытых заявок</span>. Иначе, заявки
        будут включены в <span class="doc-desc-title">Очередь открытых
        заявок</span>.

staff_identity_masking:
    title: Маскировка личности сотрудника
    content: >
        Если включено, то имя сотрудника будет скрыто из коммуникаций с клиентом.

enable_html_ticket_thread:
    title: Включить HTML в переписке в заявках
    content: >
        Включение этого параметра позволит использовать широкие возможности форматирования в общении между клиентами и
        сотрудниками.

ticket_attachment_settings:
    title: Вложения в переписке в заявках
    content: >
        Разрешить прикрепление файлов к полю <span
        class="doc-desc-title">подробностей о проблеме</span>. Эти настройки
        используются для всех новых заявок и всех новых сообщений, независимо от
        источника (веб-портал, email, api и т.д.).

max_file_size:
    title: Максимальный размер файла
    content: >
        Выберите максимальный размер файла для загрузки во вложения сотрудником. Эта настройка включает
        заготовленные вложения, статьи базы знаний и вложения в ответы на заявки.

ticket_response_files:
    title: Включать файлы в рассылку
    content: >
        Если включено, то все вложения от сотрудника будут также отправляться пользователю на email.
