#
# This is popup help messages for the Account Panel ->
#
# Fields:
# title - Shown in bold at the top of the popover window
# content - The body of the help popover
# links - List of links shows below the content
#   title - Link title
#   href - href of link (links starting with / are translated to the
#       helpdesk installation path)
#
# The key names such as 'helpdesk_name' should not be translated as they
# must match the HTML #ids put into the page template.
#
---
page_title:
    title: Оповещения и уведомления
    content: >
        Оповещения и уведомления - это автоматические рассылки электронных писем сотрудникам, в случае
        возникновения различных действий с заявкой.

ticket_alert:
    title: Оповещение о новой заявке
    content: >
        <p>
        Оповещение, отправляемое сотруднику в случае создания новой заявки.
        </p><p class="info-banner">
        <i class="icon-info-sign"></i>
        Это оповещение не рассылается если заявка автоматически назначена системой через Фильтр заявок или Разделы помощи.
        </p>
    links:
      - title: Шаблон оповещения о новой заявке по умолчанию
        href: /scp/templates.php?default_for=ticket.alert

message_alert:
    title: Оповещение о новом сообщении
    content: >
        Оповещение, отправляемое сотрудникам в случае размещения пользователем нового сообщения в существующей
        заявке.
    links:
      - title: Шаблон оповещения о новом сообщении по умолчанию
        href: /scp/templates.php?default_for=message.alert

internal_note_alert:
    title: Оповещение о новой внутренней активности
    content: >
        Оповещение, отправляемое сотрудникам в случае создания внутренней заметки или размещения ответа другим сотрудником.
    links:
      - title: Шаблон оповещения об активности по умолчанию
        href: /scp/templates.php?default_for=note.alert

assignment_alert:
    title: Оповещение о назначении заявки
    content: >
        Оповещение, отправляемое сотрудникам в случае назначения заявки.
    links:
      - title: Шаблон оповещения о назначении заявки по умолчанию
        href: /scp/templates.php?default_for=assigned.alert

transfer_alert:
    title: Оповещение о переводе заявки
    content: >
        Оповещение, отправляемое сотрудникам в случае перемещения заявки между отделами.
    links:
      - title: Шаблон оповещения о перемещении заявки по умолчанию
        href: /scp/templates.php?default_for=transfer.alert

overdue_alert:
    title: Оповещение о просроченной заявке
    content: >
        Оповещение, отправляемое сотрудникам в случае появления просроченных заявок по SLA
        или дате исполнения.
    links:
      - title: Шаблон оповещения о просроченных заявках по умолчанию
        href: /scp/templates.php?default_for=ticket.overdue

      - title: Управление SLA
        href: /scp/slas.php

system_alerts:
    title: Системные оповещения
    content: >
        Важные системные события, которые отправляются на электронную почту Администратору
        (%{config.admin_email}). Детализация событий зависит от настроек <span
        class="doc-desc-title">Уровня детализации журнала</span>, также события дублируются
        в <span class="doc-desc-title">Журналы системы</span>
    links:
      - title: Просмотр журналов системы
        href: /scp/logs.php

      - title: Изменить email администратора
        href: /scp/settings.php?t=emails
