#
# This is popup help messages for the Admin Panel -> Settings -> Knowledgebase
#
# Fields:
# title - Shown in bold at the top of the popover window
# content - The body of the help popover
# links - List of links shows below the content
#   title - Link title
#   href - href of link (links starting with / are translated to the
#       helpdesk installation path)
#
# The key names such as 'helpdesk_name' should not be translated as they
# must match the HTML #ids put into the page template.
#
---
knowledge_base_settings:
    title: Настройка базы знаний
    content: >

knowledge_base_status:
    title: Состояние базы знаний	
    content: >
        Включите этот параметр для задействования функционала базы знаний, в которой
        пользователи смогут самостоятельно искать ответы на свои вопросы.
        <br><br>
        Категории базы знаний и раздел FAQ можно сделать внутренними (просмотр только сотрудниками).
    links:
      - title: Управление базой знаний
        href: /scp/kb.php

restrict_kb:
    title: Ограничить доступ к базе знаний
    content: >
        Включите этот параметр для ограничения доступа незарегистрированных пользователей
        к статьям базы знаний в клиентской части интерфейса.
    links:
      - title: Настройки доступа
        href: /scp/settings.php?t=access

canned_responses:
    title: Заготовленные ответы
    content: >
        Включите этот параметр, чтобы разрешить сотрудникам использовать <span
        class="doc-desc-title">Заготовленные ответы</span> при ответе на заявки.
    links:
      - title: Управление заготовленными ответами
        href: /scp/canned.php
