#
# This is popup help messages for the Admin Panel -> Settings -> System page
#
# Fields:
# title - Shown in bold at the top of the popover window
# content - The body of the help popover
# links - List of links shows below the content
#   title - Link title
#   href - href of link (links starting with / are translated to the
#       helpdesk installation path)
#
# The key names such as 'helpdesk_name' should not be translated as they
# must match the HTML #ids put into the page template.
#
---
# Authentication settings
password_reset:
    title: Политика срока действия пароля
    content: >
        Определяет как часто (в месяцах) сотрудники должны менять свои пароли.
        Если параметр отключен (режим "Без срока действия"), то пароли будут
        действовать без ограничений по времени.

password_expiration_policy:
    title: Политика срока действия пароля
    content: >
        Определяет как часто сотрудники должны менять свои пароли.
        Если параметр отключен (режим <span class="doc-desc-opt">Без срока действия</span>), то пароли будут
        действовать без ограничений по времени.	

allow_password_resets:
    title: Разрешить сброс пароля
    content: >
        Включите этот параметр для того, чтобы задействовать функционал кнопок
        <span class="doc-desc-title">Забыл свой пароль</span>, после неудачной попытки входа в
        <span class="doc-desc-title">Панель управления сотрудника</span>.

reset_token_expiration:
    title: Окно сброса пароля
    content: >
        Укажите временной интервал (в минутах), в течение которого будет функционировать <span class="doc-desc-title">
        Маркер сброса пароля</span>. В случае запроса сотрудником <span
        class="doc-desc-title">Сброса пароля</span>, ему будет выслано письмо содержащее маркер, который
        позволит произвести сброс пароля.

staff_session_timeout:
    title: Максимальное время сеанса сотрудника
    content: >
        Укажите максимальное время простоя (в минутах) до того, как сотруднику потребуется
        повторный вход в систему.
        <br><br>
        Для отключения <span class="doc-desc-title">Максимального времени сеанса сотрудника</span> укажите 0.

client_session_timeout:
    title: Максимальное время сеанса пользователя
    content: >
        Укажите максимальное время простоя (в минутах) до того, как пользователю потребуется
        повторный вход в систему.
        <br><br>
        Для отключения <span class="doc-desc-title">Максимального времени сеанса пользователя</span> укажите 0.

bind_staff_session_to_ip:
    title: Закреплять сеанс сотрудника за IP
    content: >
        Включите этот параметр для того, чтобы сотрудник запоминался по IP адресу во время
        входа в систему.
        <br><br>
        Настройка этого параметра не рекомендуется для пользователей с динамическим IP.

registration_method:
    title: Тип регистрации
    content: >
        Параметры <span class="doc-desc-title">Тип регистрации</span> и <span
        class="doc-desc-title">Обязательная регистрация</span> используются
        для настройки модели регистрации и доступа к веб-порталу системы. Ниже в таблице приведена сводка, как
        эти параметры воспринимаются системой.
        <table border="1" cellpadding="2px" cellspacing="0" style="margin-top:7px"
            ><tbody style="vertical-align:top;">
            <tr><th>Обязательная регистрация</th>
                <th>Тип регистрации</th>
                <th>Результат</th></tr>
            <tr><td>Нет</td><td>Открытая</td>
                <td>Регистрация предлагается, но не является обязательной для создания
                    новых заявок.</td></tr>
            <tr><td>Да</td><td>Открытая</td>
                <td>Регистрация и вход требуются для создания новых заявок</td></tr>
            <tr><td>Нет</td><td>Закрытая</td>
                <td>Любой может создать заявку, но только сотрудники смогут создать
                    учетную запись</td></tr>
            <tr><td>Да</td><td>Закрытая</td>
                <td>Доступ пользователей только по приглашению</td></tr>
            <tr><td>Нет</td><td>Отключена</td>
                <td>Никто не сможет создать учетную запись, но любой сможет
                    создать заявку. <em>Так работает osTicket до версии 1.9</em></td></tr>
            <tr><td>Да</td><td>Disabled</td>
                <td>Отключить создание заявок через веб-портал</td></tr>
        </tbody></table>

client_verify_email:
    title: Требовать проверки email
    content: >
        Отключите этот параметр для того, чтобы дать вашим пользователям незамедлительный доступ к
        заявкам на странице "Проверить состояние заявки" в клиентской части портала. Если этот параметр включен
        (по умолчанию включен), то пользователям потребуется ввода адреса электронной почты, на который будет
        высылаться ссылка с доступом к заявке.
        <br><br>
        Отключение проверки email может повлечь за собой подделку владельца заявки.
