#
# This is popup help messages for the Account Panel ->
#
# Fields:
# title - Shown in bold at the top of the popover window
# content - The body of the help popover
# links - List of links shows below the content
#   title - Link title
#   href - href of link (links starting with / are translated to the
#       helpdesk installation path)
#
# The key names such as 'helpdesk_name' should not be translated as they
# must match the HTML #ids put into the page template.
#
---
company_information:
    title: Информация о компании
    content: >
        Здесь приведена информация о компании, которая использует преимущества системы
        osTicket и ее работников. Информация, которая здесь указана, будет отображена
        в подписи к электронным письмам (в подвале) от сотрудников, которые отвечают на заявки.
    links:
      - title: Информация о компании
        href: /scp/forms.php?type=C

landing_page:
    title: Главная страница
    content: >
        <span class="doc-desc-title">Главная страница</span> отображается
        на центральной странице вашего сайта.

offline_page:
    title: Страница обслуживания
    content: >
        <span class="doc-desc-title">Страница обслуживания</span> отображается в
        случае если система отключена, смотрите меню Панель администратора
        -&gt; Настройка -&gt; Система -&gt; Состояние системы заявок.

default_thank_you_page:
    title: Страница благодарности
    content: >
        <span class="doc-desc-title">Страница благодарности</span> отображается для
        <span class="doc-desc-title">Клиентов</span> разместивших новую заявку.
        <br/><br/>
        <span class="doc-desc-title">Страница благодарности</span> может быть
        связана с разделом помощи.

logos:
    title: Логотипы
    content: >
        Вы можете настроить <span class="doc-desc-title">Логотип</span>, который будет
        отображаться в клиентской части портала (например, Сайт поддержки).

upload_a_new_logo:
    title: Загрузить логотип
    content: >
        Выберите изображение в формате .gif, .jpg или .png. Мы изменим размер изображения
        соблюдая пропорции. При этом данные изображения не будут изменены.
        Тем не менее, для увеличения скорости загрузки рекомендуется размер изображения близкий
        к стандартному (817px &times; 170px).
